### ISSUE TITLE
FPS drops to 0 every 2- 3 seconds of recording

### ISSUE THREAD

**Issue by cuddylier** [jasaw/motioneyeos#2]
Hi

This hardware accelerated version is a vast improvement on the normal motioneyeos version so that's great but for me it's still not perfect in terms of recording.

My config:
- Raspberry Pi3
- Raspberry PI camera
- Resolution: 800 x 600
- Frame Rate: 20
- Movie Quality: 75%

I get the full FPS for around 2 - 3 seconds then the FPS appears to drop to 0 and then it goes back up to around 20 for another 2 - 3 seconds and so on.

I watched CPU usage while this was happening and didn't really see anything significant, 60 - 80% or thereabouts constantly.

Thanks

**Comment by jasaw** [comment]
Please run the latest pre-release version if you're not already on it. I've fixed a movie playback issue where the frame rate would go wrong in certain scenarios.

How did you get the frame rate? Have you tried using ffprobe or a movie player program to get the frame rate?

As a test, try closing your web browser, wait for the CPU usage to drop, then trigger some motion. On a Pi3, when there's no motion no web browser connection no live streaming, motion software should only utilize 10% of the CPU. Now trigger some motion, let it finish recording the movie, and check the frame rate of the movie. Please report back what frame rate you're getting.

What's your motion detection configuration?
If your "captured after" is set too low, you will see the movie skipping frames when the amount of motion detected is around the threshold set, which gives a horrible playback experience.

Here's my motion configuration that's been working quite well for me:
- Frame change threshold : 4%
- Minimum motion frames : 15 frames
- Motion gap : 90
- Captured before : 1 frame (higher number takes up more RAM)
- Captured after : 600 frames

**Comment by cuddylier** [comment]
Changing those settings seemed to help drastically, issue has disappeared although I did disable still images at the same time so not clear if that had an impact at all too.

Thank you very much.

**Comment by cuddylier** [comment]
I just enabled still image capture and the problem came back so seems like still images are causing it solely.

The amounts of still images produced is massive, do you know anyway to reduce the amount? I have upload to dropbox enabled so not sure if that makes the still image thing worse too due to the sheer number of uploading tasks.

**Comment by jasaw** [comment]
Looks like the frame rate dropped either because of high CPU load or limited IO bandwidth.
I haven't checked the source code, but I'm pretty sure the still images are encoded in CPU, which can load up the CPU. If the CPU can't keep up, it starts dropping frames.
On the IO side, writing large amount of data to microSD card can be slow. Last time I tested, I was only able to achieve 10 MBps (very roughly) with my class 10 microSD. Try decreasing the JPEG quality and see if it makes any difference.

**Comment by jasaw** [comment]
All my patches are in the official motionEyeOS pre-release 20171008.
