### ISSUE TITLE
Auth not possible after initial deployment

### ISSUE THREAD

**Issue by nighty2k7** [jasaw/motioneyeos#3]
Hi,

you mentioned it, I just wanted to repeat priority of the following:

I have changed password für admin and surv. user, after that point there is no way of logging into the system again, not with cache refreshing/different browser etc.
So currently after setting passwords the system seeems closed/inaccessible.

Nighty

**Comment by nighty2k7** [comment]
Otherwise: Recording quality is NICE!

**Comment by jasaw** [comment]
Appears that authentication is a known problem with upstream motionEye. I'm not sure what's causing the problem yet. I'll try to reproduce the problem here when I get some time.

Very glad to know that the improved recording is working for you too. Thank you for testing it.

**Comment by jasaw** [comment]
I can't reproduce the problem. It would be helpful if you could provide information to the below questions:
- which Raspberry Pi hardware are you using?
- please provide step-by-step on what you did to get your system into the inaccessible state. Something like Initial boot, login as admin with no password, change admin password and user password, reboot system? Please include details on the actual passwords you used.
- did you change any other configuration before it became inaccessible?

**Comment by nighty2k7** [comment]
Just as a little feedback. I am now back to your last build and the system is up and running (without passwords set). I have backed up the configuration and could give it a try,
In light of your new release ("minus the password changes"). Should I rather use that build?

Btw: RPi2/8GB SD, modest overclock,USB Wifi with antenna

**Comment by jasaw** [comment]
@nighty2k7 Wow, you're quick. I've just done the pre-release a few minutes ago. I've just started testing it. Whether you should be using it, depends on whether you're willing to reflash your SD card if it doesn't work.

I've gone through the changes from before password was problematic, and appears that there are lots of changes done related to password. I've removed all those just as a workaround for now.

**Comment by nighty2k7** [comment]
I guess I'll try settings passwords today evening  and document the process. If its messed up again after that I'll jump to your new release.

**Comment by nighty2k7** [comment]
Feedback:
This time it works without problems: password set for user admin, surveillance user changed from "user" to "surv", same password as for the admin account. Can log in.
Only change: I switched from a Edimax nano USB wifi stick to a Edimax stick with antenna, because the nano one gave me a flaky connection.

**Comment by jasaw** [comment]
@nighty2k7 Is this with my previous pre-release with problematic password?

**Comment by nighty2k7** [comment]
With the previous build. I also disabled Samba and FTP now and have all the settings enabled the previously left me with the unaccessible system. Shall I switch to your newer build to help you test?

**Comment by jasaw** [comment]
If you're not having anymore password problem with the previous pre-release, please stick to that instead.

**Comment by timdonovanuk** [comment]
With the latest release I cannot enable Advanced Settings. When I hit apply: "An error occurred. Refreshing is recommended". The motioneye.log shows: 

2017-09-22 15:33:21: [motioneye]    ERROR: 'admin_password'
Traceback (most recent call last):
  File "/home/jooaun/work/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
  File "/home/jooaun/work/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1627, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 271, in post
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 179, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 500, in set_config
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 393, in set_main_config
  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 646, in main_ui_to_dict
KeyError: 'admin_password'
2017-09-22 15:33:21: [motioneye]    ERROR: 500 POST /config/0/set/?_=1506094394892&_username=admin&_signature=5b3bf08c2f6ff86d815cb0b040349acddecbe198 (192.168.1.31) 25.30ms

**Comment by jasaw** [comment]
@timdonovanuk Please clear browser cache and try again.

**Comment by jasaw** [comment]
All my patches are in the official motionEyeOS pre-release 20171008.
